language: node_js

git:
  autocrlf: input

os:
  - "linux"
  - "windows"
  - "osx"

node_js:
  - "10"
  - "12"
  - "14"

jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: npm run coverage:ci
